In [1]:
# importing libraries
import numpy as np # for methametical operations 
import matplotlib.pyplot as plot # to plot charts
import pandas as pd # to import and manage dataset 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
import warnings
warnings.filterwarnings('ignore')

dataset = pd.read_csv('parkinsons.data.csv')
dataset.info()
# X = dataset.iloc[:, :-17:].values
X = dataset.drop(['status', 'name'], axis=1)
#X = dataset.drop(['name'], axis=1)
Y = dataset.iloc[:, 17].values

# Bar plot for Class variable
import seaborn as sb
sb.countplot(dataset['status'].values)
plot.xlabel('Class Values')
plot.ylabel('Class Counts')
plot.show()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.30, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
ssc = StandardScaler()
X_train = ssc.fit_transform(X_train)
X_test = ssc.transform(X_test)

#plot correlation heatmap plot
import seaborn #import seaborn as heatmap
corr = X.corr() 
plot.figure(figsize=(8,8))
seaborn.heatmap(X.corr(), annot=True, cmap="coolwarm").set_title('Heatmap for Parkinsons dataset')

# Feature selection as per Corrrelation value (>=0.9)
df = pd.DataFrame(X) 
X= df[['spread1', 'PPE', 'MDVP:Jitter(%)','MDVP:Jitter(Abs)', 'MDVP:RAP','MDVP:PPQ','Jitter:DDP','MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5','MDVP:APQ', 'Shimmer:DDA' ]] 
X.info()
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.30, random_state = 0)
# Feature Scaling
from sklearn.preprocessing import StandardScaler
ssc = StandardScaler()
X_train = ssc.fit_transform(X_train)
X_test = ssc.transform(X_test)


 




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
name                195 non-null object
MDVP:Fo(Hz)         195 non-null float64
MDVP:Fhi(Hz)        195 non-null float64
MDVP:Flo(Hz)        195 non-null float64
MDVP:Jitter(%)      195 non-null float64
MDVP:Jitter(Abs)    195 non-null float64
MDVP:RAP            195 non-null float64
MDVP:PPQ            195 non-null float64
Jitter:DDP          195 non-null float64
MDVP:Shimmer        195 non-null float64
MDVP:Shimmer(dB)    195 non-null float64
Shimmer:APQ3        195 non-null float64
Shimmer:APQ5        195 non-null float64
MDVP:APQ            195 non-null float64
Shimmer:DDA         195 non-null float64
NHR                 195 non-null float64
HNR                 195 non-null float64
status              195 non-null int64
RPDE                195 non-null float64
DFA                 195 non-null float64
spread1             195 non-null float64
spread2             195 non-null floa

<Figure size 640x480 with 1 Axes>

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 13 columns):
spread1             195 non-null float64
PPE                 195 non-null float64
MDVP:Jitter(%)      195 non-null float64
MDVP:Jitter(Abs)    195 non-null float64
MDVP:RAP            195 non-null float64
MDVP:PPQ            195 non-null float64
Jitter:DDP          195 non-null float64
MDVP:Shimmer        195 non-null float64
MDVP:Shimmer(dB)    195 non-null float64
Shimmer:APQ3        195 non-null float64
Shimmer:APQ5        195 non-null float64
MDVP:APQ            195 non-null float64
Shimmer:DDA         195 non-null float64
dtypes: float64(13)
memory usage: 19.9 KB


In [2]:
print ('---------------------------------------------------------------------------')
# Naive-Bayes classifier
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train) 
# Predicting the Test set results
y_pred = nb.predict(X_test)
# Confusion-Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix of Naive Bayer -------")
print(cm)
print ('Accuracy Score :')
print(accuracy_score(y_test, y_pred) ) 
print ('Report : ')
print ( classification_report(y_test, y_pred) ) 

print ('---------------------------------------------------------------------------')
# KNN classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix of KNN -------")
print(cm)
print ('Accuracy Score :')
print(accuracy_score(y_test, y_pred) ) 
print ('Report : ')
print ( classification_report(y_test, y_pred) ) 

print ('---------------------------------------------------------------------------')
# SVM classifier
from sklearn.svm import SVC
svm = SVC(kernel='linear', random_state=0)
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix of SVM -------")
print(cm)
print ('Accuracy Score :')
print(accuracy_score(y_test, y_pred) ) 
print ('Report : ')
print ( classification_report(y_test, y_pred) ) 

print ('---------------------------------------------------------------------------')
# Kernel SVM classifier
from sklearn.svm import SVC
ksvm = SVC(kernel='rbf', random_state=0)
ksvm.fit(X_train, y_train)
y_pred = ksvm.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix of Kernel SVM -------")
print(cm)
print ('Accuracy Score :')
print(accuracy_score(y_test, y_pred) ) 
print ('Report : ')
print ( classification_report(y_test, y_pred) ) 


---------------------------------------------------------------------------
Confusion matrix of Naive Bayer -------
[[13  0]
 [19 27]]
Accuracy Score :
0.6779661016949152
Report : 
              precision    recall  f1-score   support

           0       0.41      1.00      0.58        13
           1       1.00      0.59      0.74        46

    accuracy                           0.68        59
   macro avg       0.70      0.79      0.66        59
weighted avg       0.87      0.68      0.70        59

---------------------------------------------------------------------------
Confusion matrix of KNN -------
[[11  2]
 [ 2 44]]
Accuracy Score :
0.9322033898305084
Report : 
              precision    recall  f1-score   support

           0       0.85      0.85      0.85        13
           1       0.96      0.96      0.96        46

    accuracy                           0.93        59
   macro avg       0.90      0.90      0.90        59
weighted avg       0.93      0.93      0.93    

In [3]:
from sklearn.ensemble import RandomForestClassifier
Rndm_Frst = RandomForestClassifier(n_estimators=400, random_state=11)
Rndm_Frst.fit(X_train,y_train)
y_pred = Rndm_Frst.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix of RandomForestClassifier -------")
print(cm)
print ('Accuracy Score :')
print(accuracy_score(y_test, y_pred) ) 
print ('Report : ')
print ( classification_report(y_test, y_pred) ) 

Confusion matrix of RandomForestClassifier -------
[[ 9  4]
 [ 1 45]]
Accuracy Score :
0.9152542372881356
Report : 
              precision    recall  f1-score   support

           0       0.90      0.69      0.78        13
           1       0.92      0.98      0.95        46

    accuracy                           0.92        59
   macro avg       0.91      0.84      0.86        59
weighted avg       0.91      0.92      0.91        59



In [4]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
clf = MLPClassifier(random_state=0)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix of Neural_Network-------")
print(cm)
print ('Accuracy Score :')
print(accuracy_score(y_test, y_pred) ) 
print ('Report : ')
print ( classification_report(y_test, y_pred) ) 

Confusion matrix of Neural_Network-------
[[ 9  4]
 [ 0 46]]
Accuracy Score :
0.9322033898305084
Report : 
              precision    recall  f1-score   support

           0       1.00      0.69      0.82        13
           1       0.92      1.00      0.96        46

    accuracy                           0.93        59
   macro avg       0.96      0.85      0.89        59
weighted avg       0.94      0.93      0.93        59

